name: Auto Link Generator

on:
  # Allows the frontend to trigger this
  repository_dispatch:
    types: [create-short-link]
  
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  create_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Generate Random ID & Update DB
        run: |
          # 1. Get the destination URL from the request
          DEST_URL="${{ github.event.client_payload.url }}"

          # 2. Generate a random 5-character ID (Letters & Numbers)
          NEW_ID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 5 | head -n 1)

          # 3. Read the existing database
          if [ -f "db.json" ]; then
            # Remove the last '}' so we can append
            sed -i '$ s/}$//' db.json
            # Add the new entry with a comma
            echo ",\n  \"$NEW_ID\": \"$DEST_URL\"\n}" >> db.json
          else
            # Create new file if it doesn't exist
            echo "{\n  \"$NEW_ID\": \"$DEST_URL\"\n}" > db.json
          fi

          # 4. Save the new ID to an output file (to send back to frontend)
          echo $NEW_ID > new_id.txt

          # 5. Commit the changes
          git config user.name "Link Bot"
          git config user.email "bot@github.com"
          git add db.json
          git commit -m "Added short link: $NEW_ID"
          git push

      - name: Wait for GitHub Pages update (Optional buffer)
        run: sleep 10

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

  deploy:
    needs: create_link
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
